name = "UnitfulLsqFit"
uuid = "6e91b01a-d082-45f2-b6f6-60f8760dee27"
authors = ["David Gustavsson <david.e.gustavsson@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
LsqFit = "<1"
Unitful = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
